# ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼ã®è£œå®Œã‚’è¨­å®šã‚¹ã‚­ãƒ¼ãƒã«åˆã‚ã›ã¦å–å¾—
"$schema" = 'https://starship.rs/config-schema.json'

# ã‚·ã‚§ãƒ«ã®ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’æŒ¿å…¥ã™ã‚‹
add_newline = true

# ref https://github.com/starship/starship/discussions/1107?sort=top#discussioncomment-10214050
format = """
[â•­{owo} ](bold green)$username$directory$battery$all$line_break$character"""

[character]
success_symbol = '[â•°â”€>](bold green)'
error_symbol = '[x >](bold red)'

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'

# ref https://zenn.dev/link/comments/ced6da507bf16f
[git_status]
format = '$all_status$ahead_behind '
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = '[âœ“](bold green)'
untracked = ''
stashed = ''
modified = 'ğŸ”¥'
staged = ''
renamed = ''
deleted = ''

[time]
disabled = false
format = 'ğŸ•™ [$time]($style) '
time_format = '%m/%d %R'

[aws]
disabled = true

[gcloud]
disabled = true
